import { MdVisibility } from 'react-icons/md';
import { MdFavoriteBorder } from 'react-icons/md';

export const Technology = {
	id: 1,
	category: 'Tecnologia',
	title: 'Computer',
	Icon: <MdFavoriteBorder style={{ fontSize: '20px' }} />,
	headingImg: '/assets/twitter.jpg',
	headingExcept: ' Lorem ipsum dolor sit amet consectetur.Eum, itaque corporis.',
	headingAuthor: 'Davis Miller',
	headingDate: '10 Jan, 2023',
	image1: '/assets/technology-02.jpg',
	image1Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit Eum, itaque corporis.',
	image1Author: 'Smith Martinez',
	image1Date: '07 Jan, 2023',
	image2: '/assets/technology-03.jpg',
	image2Except: 'Lorem ipsum dolor sit amet consectetur adipisicing eli Eum, itaque corporis.',
	image2Author: 'Jackson Moore',
	image2Date: '03 Jan, 2023',
	image3: '/assets/technology-04.jpg',
	image3Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit Eum, itaque corporis.',
	image3Author: 'Courtney Jones',
	image3Date: '05 Dec, 2022',
	image4: '/assets/technology-05.jpg',
	image4Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit Eum, itaque corporis.',
	image4Author: 'Madison Barker',
	image4Date: '30 Nov, 2022',
};

export const Sports = {
	id: 1,
	category: 'Desporto',
	title: 'Sports',
	Icon: <MdVisibility style={{ fontSize: '20px' }} />,
	headingImg: '/assets/ronaldo.jpg',
	headingExcept: " CR7's Saudi move marks Asian game's rise, superstar's decline",
	headingAuthor: 'Davis Miller',
	headingDate: '10 Jan, 23',
	image1: '/assets/sports-02.jpg',
	image1Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
	image1Author: 'Smith Martinez',
	image1Date: '07 Jan, 23',
	image2: '/assets/sports-03.jpg',
	image2Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
	image2Author: 'Jackson Moore',
	image2Date: '03 Jan, 23',
	image3: '/assets/sports-04.jpg',
	image3Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
	image3Author: 'Courtney Jones',
	image3Date: '05 Dec, 22',
	image4: '/assets/sports-05.jpg',
	image4Except: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
	image4Author: 'Madison Barker',
	image4Date: '30 Nov, 22',
};

export const Photo = {
	id: 1,
	image1: '/assets/photo-gallery-02.jpg',
	image1Author: 'Smith Martinez',
	image1Date: '07 Jan, 2023',
	image2: '/assets/photo-gallery-03.jpg',
	image2Author: 'Jackson Moore',
	image2Date: '03 Jan, 2023',
	image3: '/assets/photo-gallery-04.jpg',
	image3Author: 'Courtney Jones',
	image3Date: '05 Dec, 2022',
};
